/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.pr.senaccadastros.gui;

import br.pr.senaccadastros.dao.EstadoDAO;
import br.pr.senaccadastros.model.Estado;
import br.pr.senaccadastros.modeltable.PesquisarEstadoModelTable;
import br.pr.senaccadastros.utils.CellRenderer;
import br.pr.senaccadastros.utils.Constantes;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author welly
 */
public class CadastroEstadoPesquisar extends javax.swing.JDialog {
    
    private Estado estadoSelecionado;
    private List<Estado> lista;
    private String pesquisa;
    
    /**
     * Creates new form CadastroEstadoPesquisar
     */
    public CadastroEstadoPesquisar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setVisible(true);
    
        jButtonAlterarEstado.setEnabled(false);
        jButtonExcluirEstado.setEnabled(false);
        jButtonSalvarEstado.setEnabled(false);
        jTextFieldNomeEstado.setEnabled(false);
        jTextFieldSiglaAlterarEstado.setEnabled(false);
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeEstado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstado = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonLimparEstado = new javax.swing.JButton();
        jButtonPesquisaEstado = new javax.swing.JButton();
        jButtonFecharEstado = new javax.swing.JButton();
        jButtonAlterarEstado = new javax.swing.JButton();
        jButtonExcluirEstado = new javax.swing.JButton();
        jButtonSalvarEstado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSiglaAlterarEstado = new javax.swing.JTextField();
        jTextFieldNomeAlterarEstado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Estado"));

        jLabel3.setText("Nome:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNomeEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTableEstado.setModel(new br.pr.senaccadastros.modeltable.PesquisarEstadoModelTable());
        jTableEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableEstadoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEstado);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonLimparEstado.setText("Limpar");
        jButtonLimparEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparEstadoActionPerformed(evt);
            }
        });

        jButtonPesquisaEstado.setText("Pesquisar");
        jButtonPesquisaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaEstadoActionPerformed(evt);
            }
        });

        jButtonFecharEstado.setText("Fechar");
        jButtonFecharEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharEstadoActionPerformed(evt);
            }
        });

        jButtonAlterarEstado.setText("Alterar");
        jButtonAlterarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarEstadoActionPerformed(evt);
            }
        });

        jButtonExcluirEstado.setText("Excluir");
        jButtonExcluirEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirEstadoActionPerformed(evt);
            }
        });

        jButtonSalvarEstado.setText("Salvar");
        jButtonSalvarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSalvarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPesquisaEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonLimparEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluirEstado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAlterarEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonFecharEstado)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPesquisaEstado)
                    .addComponent(jButtonExcluirEstado)
                    .addComponent(jButtonLimparEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterarEstado)
                    .addComponent(jButtonFecharEstado)
                    .addComponent(jButtonSalvarEstado))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setText("Nome:");

        jLabel2.setText("Sigla:");

        jTextFieldNomeAlterarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeAlterarEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSiglaAlterarEstado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jTextFieldNomeAlterarEstado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeAlterarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSiglaAlterarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharEstadoActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFecharEstadoActionPerformed

    private void jButtonExcluirEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirEstadoActionPerformed
        try{
            EstadoDAO estadoDAO = new EstadoDAO();
            estadoDAO.excluir(estadoSelecionado);
            executarPesquisa("");
            reset();
            jButtonAlterarEstado.setEnabled(false);
            jButtonExcluirEstado.setEnabled(false);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,Constantes.MSG_ERRO_SALVAR_REGISTRO + e.getMessage(),this.getTitle(),JOptionPane.ERROR_MESSAGE);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirEstadoActionPerformed

    private void jTextFieldNomeAlterarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeAlterarEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeAlterarEstadoActionPerformed

    private void jButtonLimparEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparEstadoActionPerformed
        reset();
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimparEstadoActionPerformed

    private void jButtonPesquisaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaEstadoActionPerformed
        try {
            if(jTextFieldNomeEstado.getText()== null||"".equals(jTextFieldNomeEstado.getText())){
                
                executarPesquisa("");
                jButtonAlterarEstado.setEnabled(true);
                jButtonExcluirEstado.setEnabled(true);
                
            }else{
                executarPesquisa(jTextFieldNomeEstado.getText());
                jButtonAlterarEstado.setEnabled(true);
                jButtonExcluirEstado.setEnabled(true);
            }
            
        }catch(Exception e){
            PesquisarEstadoModelTable tableModel = (PesquisarEstadoModelTable) jTableEstado.getModel();
            tableModel.removeAll();
            tableModel.fireTableDataChanged();
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisaEstadoActionPerformed

    private void jTableEstadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstadoMousePressed
        selecionarEstado();
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableEstadoMousePressed

    public void selecionarEstado(){
        try{
            int row = jTableEstado.getSelectedRow();
            PesquisarEstadoModelTable tableModel = (PesquisarEstadoModelTable) jTableEstado.getModel();
            estadoSelecionado = tableModel.getAt(row);
        }catch(Exception e){
            estadoSelecionado = null;
        }
    }
    
    private void organizarColunasTabela() {
        TableColumn column = jTableEstado.getColumnModel().getColumn(1);
        column.setPreferredWidth(350);
        jTableEstado.setDefaultRenderer(Object.class, new CellRenderer());
    }
    
    private void resetPesquisa() {
        jTextFieldNomeEstado.setText(null);
        PesquisarEstadoModelTable tableModel = (PesquisarEstadoModelTable) jTableEstado.getModel();
        jTableEstado.setPreferredSize(new Dimension(300, 64));
        tableModel.removeAll();
        tableModel.fireTableDataChanged();
    }
    public void carregarTabela() {
        
        try {
            EstadoDAO estadoDAO = new EstadoDAO();
            List<Estado> lista = estadoDAO.buscarTodos();
            
            PesquisarEstadoModelTable tableModel = (PesquisarEstadoModelTable) jTableEstado.getModel();
            if (lista.isEmpty()) {
                jTableEstado.setPreferredSize(new Dimension(300, 64));
                tableModel.removeAll();
                tableModel.fireTableDataChanged();
            } else {
                tableModel.setGridBusca(lista);
                jTableEstado.setPreferredSize(new Dimension(300, lista.size() * 17));
                tableModel.fireTableDataChanged();
            }
        } catch (Exception e) {
        }
    }
    
    private void jButtonAlterarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarEstadoActionPerformed
        if(estadoSelecionado != null){
            jButtonSalvarEstado.setEnabled(true);
            jButtonExcluirEstado.setEnabled(true);
            jTextFieldNomeEstado.setEnabled(true);
            jTextFieldSiglaAlterarEstado.setEnabled(true);
            
        
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAlterarEstadoActionPerformed

    private void jButtonSalvarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalvarEstadoActionPerformed

    public void executarPesquisa(String perquisa) throws Exception{
        
        List<Estado> Lista = new ArrayList<Estado>();
        PesquisarEstadoModelTable tableModel = (PesquisarEstadoModelTable) jTableEstado.getModel();
        
        EstadoDAO estadoDAO = new EstadoDAO();
        if(pesquisa == null || pesquisa.equals("")){
            lista = estadoDAO.buscarTodos();
        } else {
            lista = estadoDAO.buscarPorNome(pesquisa);
        }
        
        if(lista.isEmpty()){
            tableModel.removeAll();
            tableModel.fireTableChanged();
        }else{
            tableModel.setGridBusca(Lista);
            jTableEstado.setPreferredSize(new Dimension(new Dimension( 300,lista.size() * 17)));
            tableModel.fireTableDataChanged();
        }
        

    }
    public void reset(){
        estadoSelecionado = null;
        jTextFieldNomeAlterarEstado.setText(null);
        jTextFieldNomeEstado.setText(null);
        jTextFieldSiglaAlterarEstado.setText(null);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEstadoPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEstadoPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEstadoPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEstadoPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroEstadoPesquisar dialog = new CadastroEstadoPesquisar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarEstado;
    private javax.swing.JButton jButtonExcluirEstado;
    private javax.swing.JButton jButtonFecharEstado;
    private javax.swing.JButton jButtonLimparEstado;
    private javax.swing.JButton jButtonPesquisaEstado;
    private javax.swing.JButton jButtonSalvarEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstado;
    private javax.swing.JTextField jTextFieldNomeAlterarEstado;
    private javax.swing.JTextField jTextFieldNomeEstado;
    private javax.swing.JTextField jTextFieldSiglaAlterarEstado;
    // End of variables declaration//GEN-END:variables


}
